### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by A-AFTAHI** [gdbinit/otool-ng#2]
Hey, i can't compile otool on kali linux. after running make in otool directory i get the following error: 

Makefile:88: target '.' given more than once in the same rule
cc -Os -DLTO_SUPPORT -DOTOOL_NG_SUPPORT -g -Wall -I./../include -I. -D_MACH_I386_THREAD_STATUS_FPSTATE_LEGACY_FIELD_NAMES_ -D_ARCHITECTURE_I386_FPU_FPSTATE_LEGACY_FIELD_NAMES_    -c -o ./main.o main.c
main.c:37:10: fatal error: libc.h: No such file or directory
 #include <libc.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:63: main.o] Error 1

**Comment by gdbinit** [comment]
This is Mac only code, doesn't compile in other systems without major work.
